### ISSUE TITLE
can't close the backbee toolbar closing the log in pop in

### ISSUE THREAD

**Issue by clementbonfils** [backbee/BbCoreJs#522]
clicking on the cross of the log in pop in, i can't get back to the regular front office

**Comment by fkroockmann** [comment]
The problem is in "ToolbarBundle".
In bbtoolbar.twig, we need to verify if the session is expired too for add "data-autostart" in DOM

ping @eric-chau

**Comment by eric-chau** [comment]
@fkroockmann, I created a PR into ``backbee/backbee`` to resolve problem due to session expiration but it does not resolve issue about closing the login popin cause the token is still valid. You should do something like sending a request to destroy the session so user will be disconnected properly like we actually do with the Logout button.
